linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning

output:
  formats:
    - format: colored-line-number

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

