# Prometheus configuration for mautrix-viber monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mautrix-viber'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    
  # Optional: Monitor system resources
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

