apiVersion: v1
kind: Service
metadata:
  name: mautrix-viber
  namespace: mautrix-viber
spec:
  selector:
    app: mautrix-viber
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP

