name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Install dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Run linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --out-format=colored-line-number

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Build
      run: go build -o bin/mautrix-viber ./cmd/mautrix-viber
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: mautrix-viber
        path: bin/mautrix-viber

